name: 07 - Using Expressions
run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: '[debug] Print start-up data'
        if: ${{ inputs.debug }}
        run: |
          echo "Triggerd by: ${{ github.event_name }}"
          echo "Branch: ${{github.ref }}"
          echo "Commit SHA: ${{github.sha }}"
          echo "Runner OS: ${{ github.os }}"
      - name: '[debug] Print when triggered from main'
        if: ${{ inputs.debug && github.ref == 'refs/heads/main' }}
        run: echo "I was triggerd from main"
      - name: Greeting
        run: echo "Hello, World"

